name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kodi-version: [ nexus ]
        python-version: [ 3.8 ]
    steps:
    - name: Check out ${{ github.sha }} from repository ${{ github.repository }}
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r ./requirements.txt

    - name: Run ruff
      run: ruff check .

    - name: Run Kodi Addon checker
      run: kodi-addon-checker --branch ${{ matrix.kodi-version }} --PR
